name: Publish
on:
  release:
    types: [published]
env:
  MAVEN_PASS: ${{ secrets.MAVEN_PASS }}
jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: eskatos/gradle-command-action@v1.3.2
        with:
          gradle-version: wrapper
          arguments: build publish
          dependencies-cache-enabled: false
          configuration-cache-enabled: false
